import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.FRIKCHANGE_CONFIG||{};
const supabase=createClient(String(cfg.supabaseUrl||'').replace(/\/$/,''),String(cfg.supabaseAnonKey||''),{auth:{persistSession:true,autoRefreshToken:true}});
const root=document.getElementById('admin-root');
const css='<style>body{margin:0;background:#0b0f17;color:#e5e7eb;font-family:system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:32px}section{background:#111827;border:1px solid #243041;border-radius:18px;padding:22px;margin:18px 0}input,textarea,button{font:inherit;border-radius:10px;padding:11px;border:1px solid #334155}input,textarea{background:#0f172a;color:#fff;width:100%;box-sizing:border-box;margin:6px 0 12px}button{cursor:pointer;background:#10b981;color:#022c22;font-weight:800;margin-right:8px}.muted{color:#94a3b8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.stat{font-size:28px;font-weight:900}.danger{color:#fca5a5}.row{border-top:1px solid #243041;padding:12px 0}</style>';
function page(content){root.innerHTML=css+'<main><h1>FrikChange — Console d’administration</h1>'+content+'</main>'}
async function api(path,options={}){const {data}=await supabase.auth.getSession();const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(data.session?.access_token||''),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur serveur');return d}
function login(){page('<section><h2>Connexion administrateur</h2><p class="muted">Accès réservé aux comptes ayant le rôle admin.</p><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Mot de passe"><button id="login">Se connecter</button><p id="msg"></p></section>');document.getElementById('login').onclick=async()=>{try{const r=await supabase.auth.signInWithPassword({email:document.getElementById('email').value,password:document.getElementById('password').value});if(r.error)throw r.error;await boot()}catch(e){document.getElementById('msg').textContent=e.message}}}
async function boot(){const {data}=await supabase.auth.getSession();if(!data.session)return login();try{const [a,n]=await Promise.all([api('/api/analytics'),api('/api/admin/announcements')]);page('<div class="grid"><section><h2>Analytics</h2>'+Object.entries(a.summary||{}).map(([k,v])=>'<div class="row"><b>'+k+'</b><div class="stat">'+v+'</div></div>').join('')+'</section><section><h2>Génération marketing IA</h2><input id="topic" placeholder="Sujet"><textarea id="notes" placeholder="Notes"></textarea><button id="generate">Générer</button><pre id="out" style="white-space:pre-wrap"></pre></section></div><section><h2>Annonces officielles</h2><input id="title" placeholder="Titre"><textarea id="textFr" placeholder="Texte français"></textarea><textarea id="textAr" placeholder="Texte arabe"></textarea><button id="publish">Publier</button><div id="list">'+(n.items||[]).map(x=>'<div class="row"><b>'+escapeHtml(x.title)+'</b><div>'+escapeHtml(x.text_fr||'')+'</div><small class="muted">'+escapeHtml(x.status||'')+'</small></div>').join('')+'</div></section><button id="logout">Déconnexion</button>');document.getElementById('generate').onclick=async()=>{try{const d=await api('/api/admin/marketing',{method:'POST',body:JSON.stringify({topic:document.getElementById('topic').value,customNotes:document.getElementById('notes').value})});document.getElementById('out').textContent=JSON.stringify(d.content,null,2)}catch(e){document.getElementById('out').textContent=e.message}};document.getElementById('publish').onclick=async()=>{try{await api('/api/admin/announcements',{method:'POST',body:JSON.stringify({title:document.getElementById('title').value,textFr:document.getElementById('textFr').value,textAr:document.getElementById('textAr').value})});await boot()}catch(e){alert(e.message)}};document.getElementById('logout').onclick=async()=>{await supabase.auth.signOut();login()}}catch(e){page('<section><h2 class="danger">Accès refusé</h2><p>'+escapeHtml(e.message)+'</p></section>')}}
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
boot();