import {supabase} from './supabaseClient.js';
import {signUp,signIn,signOut,resetPassword} from './auth.js';
import {createUnlock,getUnlockedContact} from './payments.js';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const state={session:null,profile:null,view:'market'};
const ref=new URLSearchParams(location.search).get('ref')||'';
const msg=(x,e=false)=>{const t=$('#toast');t.textContent=x;t.className='toast '+(e?'error':'');setTimeout(()=>t.textContent='',4500)};
async function profile(){if(!state.session)return state.profile=null;state.profile=(await supabase.from('profiles').select('*').eq('id',state.session.user.id).maybeSingle()).data}
async function market(){let q=supabase.from('public_listings').select('*').order('created_at',{ascending:false}).limit(60);const t=$('#ft')?.value,c=$('#fc')?.value,city=$('#fci')?.value?.trim();if(t)q=q.eq('type',t);if(c)q=q.eq('currency',c);if(city)q=q.ilike('city','%'+city+'%');const {data,error}=await q;$('#market').innerHTML=error?'<div class="empty">Erreur de chargement.</div>':(data||[]).map(x=>`<article class="card"><span class="tag">${esc(x.type)}</span><h3>${esc(x.currency)} · ${esc(x.amount_range)}</h3><p>${esc(x.country)} · ${esc(x.city)}${x.neighborhood?' · '+esc(x.neighborhood):''}</p><button class="primary unlock" data-id="${x.id}">Débloquer WhatsApp</button></article>`).join('')||'<div class="empty">Aucune annonce approuvée.</div>';document.querySelectorAll('.unlock').forEach(b=>b.onclick=()=>unlock(b.dataset.id))}
async function unlock(id){try{if(!state.session){state.view='auth';render();return msg('Connectez-vous pour débloquer.',true)}const d=await createUnlock(id,supabase);if(d.alreadyUnlocked){const c=await getUnlockedContact(d.transactionId,supabase);return msg('WhatsApp : '+c.whatsapp_number)}if(d.checkoutUrl)location.href=d.checkoutUrl}catch(e){msg(e.message,true)}}
async function listings(){const {data}=await supabase.from('listings').select('*').eq('user_id',state.session.user.id).order('created_at',{ascending:false});$('#mine').innerHTML=(data||[]).map(x=>`<div class="row"><div><b>${esc(x.type)} · ${esc(x.currency)} ${esc(x.amount_range)}</b><small>${esc(x.country)} · ${esc(x.city)}</small><span class="status ${x.status.toLowerCase()}">${esc(x.status)}</span></div><div><button class="ghost edit" data-id="${x.id}">Modifier</button><button class="danger del" data-id="${x.id}">Supprimer</button></div></div>`).join('')||'<div class="empty">Aucune annonce.</div>';document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer ?')){const q=await supabase.from('listings').delete().eq('id',b.dataset.id);q.error?msg(q.error.message,true):(msg('Annonce supprimée'),listings())}});document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>form(b.dataset.id))}
async function form(id){const ex=id?(await supabase.from('listings').select('*').eq('id',id).maybeSingle()).data:null;$('#modal').innerHTML=`<div class="modal"><button class="close" onclick="closeModal()">×</button><h2>${id?'Modifier':'Publier'} une annonce</h2><form id="lf" class="form"><label>Type<select name="type"><option>OFFRE</option><option>BESOIN</option><option>VOYAGEUR_GP</option></select></label><label>Devise<input name="currency" required placeholder="MAD, XOF, EUR"></label><label>Montant / fourchette<input name="amount_range" required placeholder="1000 - 2000"></label><label>Pays<input name="country" required></label><label>Ville<input name="city" required></label><label>Quartier<input name="neighborhood"></label><label>WhatsApp<input name="whatsapp_number" required placeholder="+212..."></label><button class="primary">Enregistrer</button></form></div>`;$('#modal').classList.add('show');if(ex)for(const k of ['type','currency','amount_range','country','city','neighborhood','whatsapp_number'])$('#lf').elements[k].value=ex[k]||'';$('#lf').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));const q=id?await supabase.from('listings').update(v).eq('id',id):await supabase.from('listings').insert({...v,user_id:state.session.user.id,status:'PENDING'});if(q.error)return msg(q.error.message,true);closeModal();msg(id?'Annonce mise à jour.':'Annonce envoyée pour validation.');listings()}}
function closeModal(){$('#modal').classList.remove('show');$('#modal').innerHTML=''}window.closeModal=closeModal;window.newListing=()=>form();window.searchMarket=market;
async function payments(){const {data}=await supabase.from('unlock_transactions').select('amount_paid,currency,status,created_at').order('created_at',{ascending:false}).limit(50);$('#payments').innerHTML=(data||[]).map(x=>`<div class="row"><div><b>${Number(x.amount_paid).toFixed(2)} ${esc(x.currency)}</b><small>${new Date(x.created_at).toLocaleString('fr-FR')}</small></div><span class="status ${x.status.toLowerCase()}">${esc(x.status)}</span></div>`).join('')||'<div class="empty">Aucun paiement.</div>'}
async function ambassador(){const {data}=await supabase.from('commissions').select('*').order('created_at',{ascending:false});const total=(data||[]).reduce((s,x)=>s+Number(x.commission_amount||0),0);$('#astats').innerHTML=`<div class="stat"><b>${data?.length||0}</b><span>Commissions</span></div><div class="stat"><b>${total.toFixed(2)} MAD</b><span>Gains</span></div><div class="stat"><b>${esc(state.profile?.referral_code||'—')}</b><span>Code</span></div>` ;$('#commissions').innerHTML=(data||[]).map(x=>`<div class="row"><b>+${Number(x.commission_amount).toFixed(2)} MAD</b><span class="status available">${esc(x.status)}</span></div>`).join('')||'<div class="empty">Aucune commission pour le moment.</div>'}
function auth(){const f=$('#af'),toggle=$('#toggle');toggle.onclick=()=>{const s=toggle.dataset.signup!=='1';toggle.dataset.signup=s?'1':'0';$('#extra').hidden=!s;$('#asubmit').textContent=s?'Créer mon compte':'Se connecter';toggle.textContent=s?'J’ai déjà un compte':'Créer un compte'};$('#forgot').onclick=async()=>{try{await resetPassword($('#email').value.trim());msg('Email de réinitialisation envoyé.')}catch(e){msg(e.message,true)}};f.onsubmit=async e=>{e.preventDefault();try{if(toggle.dataset.signup==='1'){await signUp({email:$('#email').value.trim(),password:$('#password').value,fullName:$('#name').value.trim(),phone:$('#phone').value.trim(),referralCode:$('#ref').value.trim()});msg('Compte créé. Vérifiez votre email si nécessaire.')}else{await signIn($('#email').value.trim(),$('#password').value);state.session=(await supabase.auth.getSession()).data.session;await profile();state.view='dash';render()}}catch(x){msg(x.message,true)}}}
async function render(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));($('#p-'+state.view)||$('#p-market')).classList.add('active');$('#account').innerHTML=state.session?`<button class="ghost" onclick="go('dash')">Mon espace</button><button class="ghost" id="out">Déconnexion</button>`:'<button class="primary" onclick="go(\'auth\')">Connexion</button>';if($('#out'))$('#out').onclick=async()=>{await signOut();state.session=null;state.profile=null;state.view='market';render()};if(state.view==='market')market();if(state.view==='auth')auth();if(state.view==='dash'&&state.session){$('#hello').textContent=state.profile?.full_name||state.session.user.email;listings();payments()}if(state.view==='amb'&&state.session)ambassador()}
window.go=v=>{if(!state.session&&['dash','amb'].includes(v))v='auth';state.view=v;render()};window.share=()=>navigator.clipboard?.writeText(location.origin+'/?ref='+state.profile.referral_code).then(()=>msg('Lien copié.'));
(async()=>{state.session=(await supabase.auth.getSession()).data.session;await profile();supabase.auth.onAuthStateChange(async(_,s)=>{state.session=s;await profile()});render()})();